chore: amend ci changes to build & publish docker image only with change in app [skip ci]
* fix: minor fixes on app, enhance CI/CD pipeline with force build option [skip ci]

* fix: update DVC configuration and CI workflow for improved data handling and credential setup

* test: verify 1st CI run setup

* test: verify 2nd CI run setup

* test: verify final CI run setup [skip ci]

* test: [skip ci]

* chore: increase cross-validation folds to improve model evaluation accuracy [skip ci]

diff --git a/.github/workflows/model-pipeline-ci.yml b/.github/workflows/model-pipeline-ci.yml
--- a/.github/workflows/model-pipeline-ci.yml
+++ b/.github/workflows/model-pipeline-ci.yml
@@ -2,7 +2,7 @@ name: MLOps project CI/CD Pipeline
 
 on:
   push:
-    branches: [ main ]          # test multiple branches [ main, feature-ci-run ]
+    branches: [ main ]           # test multiple branches [ main, feature-ci-run ]
     paths-ignore:
       - '**.md'
       - 'docs/**'
@@ -17,6 +17,11 @@ on:
         type: choice
         options:
           - staging
+      force_build:
+        description: 'Force build even without code changes'
+        required: false
+        type: boolean
+        default: false
 
 env:
   DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
@@ -62,6 +67,15 @@ jobs:
         run: |
           python3 src/data/make_dataset.py
           dvc repro
+
+      - name: Push the data to DVC remote
+        env:
+          DVC_ACCESS_KEY: ${{ secrets.DVC_ACCESS_KEY }}
+        run: |
+          dvc remote modify origin --local access_key_id "$DVC_ACCESS_KEY"
+          dvc remote modify origin --local secret_access_key "$DVC_ACCESS_KEY"
+          dvc commit || echo "No changes to commit"
+          dvc push || { echo "DVC push failed"; exit 1; }
 
       # - name: Lint with flake8
       #   run: |
@@ -132,11 +146,36 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Check for app code changes
+        id: check_changes
+        run: |
+          echo "has_changes=false" >> $GITHUB_OUTPUT
+
+          if [[ "${{ github.event.inputs.force_build }}" == "true" ]]; then
+            echo "has_changes=true" >> $GITHUB_OUTPUT
+            echo "Force build was enabled by user, proceeding with Docker build.."
+          elif [[ "${{ github.event.before }}" == "" ]]; then
+              #First commit on branch - build anyway
+              echo "has_changes=true" >> $GITHUB_OUTPUT
+              echo "It's the very first commit on branch, hence proceeding with Docker build.."
+          else
+            git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "flask_app/" && echo "has_changes=true" >> $GITHUB_OUTPUT || echo "No changes detected in flask_app/"
+          fi
+      
+      - name: Skip build message
+        if: ${{ !steps.check_changes.outputs.has_changes }}
+        run: |
+          echo "Since no changes in flask_app directory, skipping Docker build and push"
 
       - name: Set up Docker Buildx
+        if: ${{ steps.check_changes.outputs.has_changes == 'true' }}
         uses: docker/setup-buildx-action@v3
 
       - name: Cache Docker layers
+        if: ${{ steps.check_changes.outputs.has_changes == 'true' }}
         uses: actions/cache@v4
         with:
           path: /tmp/.buildx-cache
@@ -145,12 +184,14 @@ jobs:
             ${{ runner.os }}-buildx-
 
       - name: Log in to DockerHub
+        if: ${{ steps.check_changes.outputs.has_changes == 'true' }}
         uses: docker/login-action@v3
         with:
           username: ${{ env.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
       - name: Set Release Tag
+        if: ${{ steps.check_changes.outputs.has_changes == 'true' }}
         id: vars
         run: |
           BRANCH_NAME=${GITHUB_REF#refs/heads/}
@@ -165,6 +206,7 @@ jobs:
       #     echo "IMAGE_NAME=${REPO_NAME_LOWERCASE}" >> $GITHUB_ENV
 
       - name: Build and push Docker image
+        if: ${{ steps.check_changes.outputs.has_changes == 'true' }}
         uses: docker/build-push-action@v6
         with:
           context: .
@@ -181,6 +223,7 @@ jobs:
 
       # Temporary fix for cache: https://github.com/docker/build-push-action/issues/252
       - name: Move cache
+        if: ${{ steps.check_changes.outputs.has_changes == 'true' }}
         run: |
           rm -rf /tmp/.buildx-cache
           mv /tmp/.buildx-cache-new /tmp/.buildx-cache
